// flow-typed signature: ae00b941adf06d4eddcf3a1ed80ca422
// flow-typed version: <<STUB>>/eslint-config-formidable_v^2.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-formidable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-formidable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-formidable/configurations/es5-browser' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es5-node' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es5-test' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es5' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6-browser' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6-node-test' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6-node' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6-react-test' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6-react' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6-test' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/configurations/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/best-practices/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/best-practices/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/errors/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/errors/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/es6/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/es6/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/node/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/node/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/strict/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/strict/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/style/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/style/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/variables/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/eslint/variables/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/filenames/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/filenames/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/import/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/import/on' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/react/off' {
  declare module.exports: any;
}

declare module 'eslint-config-formidable/rules/react/on' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-formidable/configurations/es5-browser.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es5-browser'>;
}
declare module 'eslint-config-formidable/configurations/es5-node.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es5-node'>;
}
declare module 'eslint-config-formidable/configurations/es5-test.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es5-test'>;
}
declare module 'eslint-config-formidable/configurations/es5.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es5'>;
}
declare module 'eslint-config-formidable/configurations/es6-browser.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6-browser'>;
}
declare module 'eslint-config-formidable/configurations/es6-node-test.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6-node-test'>;
}
declare module 'eslint-config-formidable/configurations/es6-node.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6-node'>;
}
declare module 'eslint-config-formidable/configurations/es6-react-test.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6-react-test'>;
}
declare module 'eslint-config-formidable/configurations/es6-react.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6-react'>;
}
declare module 'eslint-config-formidable/configurations/es6-test.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6-test'>;
}
declare module 'eslint-config-formidable/configurations/es6.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/es6'>;
}
declare module 'eslint-config-formidable/configurations/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/configurations/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/best-practices/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/best-practices/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/best-practices/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/best-practices/on'>;
}
declare module 'eslint-config-formidable/rules/eslint/errors/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/errors/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/errors/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/errors/on'>;
}
declare module 'eslint-config-formidable/rules/eslint/es6/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/es6/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/es6/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/es6/on'>;
}
declare module 'eslint-config-formidable/rules/eslint/node/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/node/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/node/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/node/on'>;
}
declare module 'eslint-config-formidable/rules/eslint/strict/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/strict/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/strict/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/strict/on'>;
}
declare module 'eslint-config-formidable/rules/eslint/style/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/style/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/style/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/style/on'>;
}
declare module 'eslint-config-formidable/rules/eslint/variables/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/variables/off'>;
}
declare module 'eslint-config-formidable/rules/eslint/variables/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/eslint/variables/on'>;
}
declare module 'eslint-config-formidable/rules/filenames/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/filenames/off'>;
}
declare module 'eslint-config-formidable/rules/filenames/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/filenames/on'>;
}
declare module 'eslint-config-formidable/rules/import/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/import/off'>;
}
declare module 'eslint-config-formidable/rules/import/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/import/on'>;
}
declare module 'eslint-config-formidable/rules/react/off.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/react/off'>;
}
declare module 'eslint-config-formidable/rules/react/on.js' {
  declare module.exports: $Exports<'eslint-config-formidable/rules/react/on'>;
}
