export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
export const OFFLINE_SERIALIZE = 'Offline/OFFLINE_SERIALIZE';
export const OFFLINE_STATUS_CHANGED = 'Offline/OFFLINE_STATUS_CHANGED';
export const OFFLINE_BUSY = 'Offline/OFFLINE_BUSY';
export const OFFLINE_SCHEDULE_RETRY = 'Offline/OFFLINE_SCHEDULE_RETRY';
export const OFFLINE_RESET_STATE = 'Offline/OFFLINE_RESET_STATE';
